import type { Language } from "./translations";

export type AvailabilityTranslation = {
  availableDates: string;
  manageAvailability: string;
  calendarHelp: string;
  available: string;
  booked: string;
  unavailable: string;
  notSet: string;
  previousMonth: string;
  nextMonth: string;
  checkAvailability: string;
  selectDate: string;
  checking: string;
  dateAvailable: string;
  dateBooked: string;
  dateUnavailable: string;
  availabilityNotSet: string;
  couldNotCheck: string;
  couldNotSave: string;
};

export const availabilityLocales: Record<Language, string> = {
  en: "en-GB", zh: "zh-CN", ja: "ja-JP", ko: "ko-KR",
  id: "id-ID", ms: "ms-MY", th: "th-TH", hi: "hi-IN",
  ar: "ar", vi: "vi-VN", tl: "fil-PH", pt: "pt-BR",
  es: "es-ES", fr: "fr-FR", de: "de-DE", ru: "ru-RU",
  tr: "tr-TR", it: "it-IT", nl: "nl-NL", pl: "pl-PL",
  el: "el-GR", uk: "uk-UA",
};

export const availabilityTranslations: Record<Language, AvailabilityTranslation> = {
  en: { availableDates: "Available dates", manageAvailability: "Booking calendar availability", calendarHelp: "Tap a date to cycle: Available → Booked → Unavailable → Not set.", available: "Available", booked: "Booked", unavailable: "Unavailable", notSet: "Not set", previousMonth: "Previous month", nextMonth: "Next month", checkAvailability: "Check availability", selectDate: "Select an event date to check this DJ's availability.", checking: "Checking availability...", dateAvailable: "Available on this date", dateBooked: "Already booked on this date", dateUnavailable: "Unavailable on this date", availabilityNotSet: "Availability has not been set for this date. You can still send an enquiry.", couldNotCheck: "Availability could not be checked. Please try again.", couldNotSave: "Availability could not be saved." },
  zh: { availableDates: "可用日期", manageAvailability: "预订日历", calendarHelp: "点击日期循环切换：可用 → 已预订 → 不可用 → 未设置。", available: "可用", booked: "已预订", unavailable: "不可用", notSet: "未设置", previousMonth: "上个月", nextMonth: "下个月", checkAvailability: "查看可用性", selectDate: "请选择活动日期以查看 DJ 是否有空。", checking: "正在查询...", dateAvailable: "此日期可预订", dateBooked: "此日期已被预订", dateUnavailable: "此日期不可用", availabilityNotSet: "此日期尚未设置可用性。你仍可以发送咨询。", couldNotCheck: "无法查询可用性，请重试。", couldNotSave: "无法保存可用性。" },
  ja: { availableDates: "予約可能日", manageAvailability: "予約カレンダー", calendarHelp: "日付をタップして切替：予約可能 → 予約済み → 対応不可 → 未設定。", available: "予約可能", booked: "予約済み", unavailable: "対応不可", notSet: "未設定", previousMonth: "前の月", nextMonth: "次の月", checkAvailability: "空き状況を確認", selectDate: "イベント日を選択して空き状況を確認してください。", checking: "確認中...", dateAvailable: "この日は予約可能です", dateBooked: "この日は予約済みです", dateUnavailable: "この日は対応できません", availabilityNotSet: "この日の空き状況は未設定です。お問い合わせは送信できます。", couldNotCheck: "空き状況を確認できませんでした。", couldNotSave: "空き状況を保存できませんでした。" },
  ko: { availableDates: "예약 가능 날짜", manageAvailability: "예약 일정", calendarHelp: "날짜를 눌러 변경: 예약 가능 → 예약됨 → 불가 → 미설정.", available: "예약 가능", booked: "예약됨", unavailable: "불가", notSet: "미설정", previousMonth: "이전 달", nextMonth: "다음 달", checkAvailability: "예약 가능 여부 확인", selectDate: "행사 날짜를 선택해 DJ 일정을 확인하세요.", checking: "확인 중...", dateAvailable: "이 날짜에 예약 가능합니다", dateBooked: "이 날짜는 이미 예약되었습니다", dateUnavailable: "이 날짜에는 예약할 수 없습니다", availabilityNotSet: "이 날짜의 일정이 설정되지 않았습니다. 문의는 보낼 수 있습니다.", couldNotCheck: "일정을 확인할 수 없습니다.", couldNotSave: "일정을 저장할 수 없습니다." },
  id: { availableDates: "Tanggal tersedia", manageAvailability: "Kalender pemesanan", calendarHelp: "Ketuk tanggal: Tersedia → Dipesan → Tidak tersedia → Belum diatur.", available: "Tersedia", booked: "Dipesan", unavailable: "Tidak tersedia", notSet: "Belum diatur", previousMonth: "Bulan sebelumnya", nextMonth: "Bulan berikutnya", checkAvailability: "Periksa ketersediaan", selectDate: "Pilih tanggal acara untuk memeriksa ketersediaan DJ.", checking: "Memeriksa...", dateAvailable: "Tersedia pada tanggal ini", dateBooked: "Sudah dipesan pada tanggal ini", dateUnavailable: "Tidak tersedia pada tanggal ini", availabilityNotSet: "Ketersediaan belum diatur. Anda tetap dapat mengirim pertanyaan.", couldNotCheck: "Ketersediaan tidak dapat diperiksa.", couldNotSave: "Ketersediaan tidak dapat disimpan." },
  ms: { availableDates: "Tarikh tersedia", manageAvailability: "Kalendar tempahan", calendarHelp: "Ketik tarikh: Tersedia → Ditempah → Tidak tersedia → Belum ditetapkan.", available: "Tersedia", booked: "Ditempah", unavailable: "Tidak tersedia", notSet: "Belum ditetapkan", previousMonth: "Bulan sebelumnya", nextMonth: "Bulan seterusnya", checkAvailability: "Semak ketersediaan", selectDate: "Pilih tarikh acara untuk menyemak ketersediaan DJ.", checking: "Menyemak...", dateAvailable: "Tersedia pada tarikh ini", dateBooked: "Sudah ditempah pada tarikh ini", dateUnavailable: "Tidak tersedia pada tarikh ini", availabilityNotSet: "Ketersediaan belum ditetapkan. Anda masih boleh menghantar pertanyaan.", couldNotCheck: "Ketersediaan tidak dapat disemak.", couldNotSave: "Ketersediaan tidak dapat disimpan." },
  th: { availableDates: "วันที่ว่าง", manageAvailability: "ปฏิทินการจอง", calendarHelp: "แตะวันที่เพื่อเปลี่ยน: ว่าง → จองแล้ว → ไม่ว่าง → ยังไม่กำหนด", available: "ว่าง", booked: "จองแล้ว", unavailable: "ไม่ว่าง", notSet: "ยังไม่กำหนด", previousMonth: "เดือนก่อน", nextMonth: "เดือนถัดไป", checkAvailability: "ตรวจสอบวันว่าง", selectDate: "เลือกวันที่จัดงานเพื่อตรวจสอบวันว่างของ DJ", checking: "กำลังตรวจสอบ...", dateAvailable: "ว่างในวันนี้", dateBooked: "วันนี้มีการจองแล้ว", dateUnavailable: "ไม่ว่างในวันนี้", availabilityNotSet: "ยังไม่ได้กำหนดสถานะวันนี้ คุณยังส่งคำขอได้", couldNotCheck: "ไม่สามารถตรวจสอบวันว่างได้", couldNotSave: "ไม่สามารถบันทึกวันว่างได้" },
  hi: { availableDates: "उपलब्ध तारीखें", manageAvailability: "बुकिंग कैलेंडर", calendarHelp: "तारीख दबाएँ: उपलब्ध → बुक → अनुपलब्ध → सेट नहीं।", available: "उपलब्ध", booked: "बुक", unavailable: "अनुपलब्ध", notSet: "सेट नहीं", previousMonth: "पिछला महीना", nextMonth: "अगला महीना", checkAvailability: "उपलब्धता जाँचें", selectDate: "DJ की उपलब्धता देखने के लिए कार्यक्रम की तारीख चुनें।", checking: "जाँच हो रही है...", dateAvailable: "इस तारीख को उपलब्ध", dateBooked: "इस तारीख को पहले से बुक", dateUnavailable: "इस तारीख को अनुपलब्ध", availabilityNotSet: "इस तारीख की उपलब्धता सेट नहीं है। आप फिर भी पूछताछ भेज सकते हैं।", couldNotCheck: "उपलब्धता जाँची नहीं जा सकी।", couldNotSave: "उपलब्धता सहेजी नहीं जा सकी।" },
  ar: { availableDates: "التواريخ المتاحة", manageAvailability: "تقويم الحجوزات", calendarHelp: "اضغط التاريخ للتبديل: متاح ← محجوز ← غير متاح ← غير محدد.", available: "متاح", booked: "محجوز", unavailable: "غير متاح", notSet: "غير محدد", previousMonth: "الشهر السابق", nextMonth: "الشهر التالي", checkAvailability: "تحقق من التوفر", selectDate: "اختر تاريخ الفعالية للتحقق من توفر منسق الموسيقى.", checking: "جارٍ التحقق...", dateAvailable: "متاح في هذا التاريخ", dateBooked: "محجوز بالفعل في هذا التاريخ", dateUnavailable: "غير متاح في هذا التاريخ", availabilityNotSet: "لم يتم تحديد التوفر لهذا التاريخ. لا يزال بإمكانك إرسال استفسار.", couldNotCheck: "تعذر التحقق من التوفر.", couldNotSave: "تعذر حفظ التوفر." },
  vi: { availableDates: "Ngày còn trống", manageAvailability: "Lịch đặt DJ", calendarHelp: "Chạm ngày để đổi: Còn trống → Đã đặt → Không rảnh → Chưa đặt.", available: "Còn trống", booked: "Đã đặt", unavailable: "Không rảnh", notSet: "Chưa đặt", previousMonth: "Tháng trước", nextMonth: "Tháng sau", checkAvailability: "Kiểm tra lịch", selectDate: "Chọn ngày sự kiện để kiểm tra lịch của DJ.", checking: "Đang kiểm tra...", dateAvailable: "Còn trống vào ngày này", dateBooked: "Đã được đặt vào ngày này", dateUnavailable: "Không rảnh vào ngày này", availabilityNotSet: "Chưa thiết lập lịch cho ngày này. Bạn vẫn có thể gửi yêu cầu.", couldNotCheck: "Không thể kiểm tra lịch.", couldNotSave: "Không thể lưu lịch." },
  tl: { availableDates: "Mga available na petsa", manageAvailability: "Booking calendar", calendarHelp: "Pindutin ang petsa: Available → Booked → Hindi available → Hindi nakatakda.", available: "Available", booked: "Booked", unavailable: "Hindi available", notSet: "Hindi nakatakda", previousMonth: "Nakaraang buwan", nextMonth: "Susunod na buwan", checkAvailability: "Tingnan ang availability", selectDate: "Pumili ng petsa para tingnan ang availability ng DJ.", checking: "Tinitingnan...", dateAvailable: "Available sa petsang ito", dateBooked: "Booked na sa petsang ito", dateUnavailable: "Hindi available sa petsang ito", availabilityNotSet: "Hindi pa nakatakda ang availability. Maaari ka pa ring magpadala ng inquiry.", couldNotCheck: "Hindi matingnan ang availability.", couldNotSave: "Hindi ma-save ang availability." },
  pt: { availableDates: "Datas disponíveis", manageAvailability: "Calendário de reservas", calendarHelp: "Toque numa data: Disponível → Reservada → Indisponível → Não definida.", available: "Disponível", booked: "Reservada", unavailable: "Indisponível", notSet: "Não definida", previousMonth: "Mês anterior", nextMonth: "Mês seguinte", checkAvailability: "Verificar disponibilidade", selectDate: "Selecione a data do evento para verificar a disponibilidade do DJ.", checking: "A verificar...", dateAvailable: "Disponível nesta data", dateBooked: "Já reservado nesta data", dateUnavailable: "Indisponível nesta data", availabilityNotSet: "A disponibilidade não foi definida. Ainda pode enviar um pedido.", couldNotCheck: "Não foi possível verificar a disponibilidade.", couldNotSave: "Não foi possível guardar a disponibilidade." },
  es: { availableDates: "Fechas disponibles", manageAvailability: "Calendario de reservas", calendarHelp: "Pulsa una fecha: Disponible → Reservada → No disponible → Sin definir.", available: "Disponible", booked: "Reservada", unavailable: "No disponible", notSet: "Sin definir", previousMonth: "Mes anterior", nextMonth: "Mes siguiente", checkAvailability: "Consultar disponibilidad", selectDate: "Selecciona la fecha del evento para consultar la disponibilidad del DJ.", checking: "Consultando...", dateAvailable: "Disponible en esta fecha", dateBooked: "Ya está reservado en esta fecha", dateUnavailable: "No disponible en esta fecha", availabilityNotSet: "No se ha definido la disponibilidad. Aún puedes enviar una consulta.", couldNotCheck: "No se pudo consultar la disponibilidad.", couldNotSave: "No se pudo guardar la disponibilidad." },
  fr: { availableDates: "Dates disponibles", manageAvailability: "Calendrier des réservations", calendarHelp: "Touchez une date : Disponible → Réservée → Indisponible → Non définie.", available: "Disponible", booked: "Réservée", unavailable: "Indisponible", notSet: "Non définie", previousMonth: "Mois précédent", nextMonth: "Mois suivant", checkAvailability: "Vérifier la disponibilité", selectDate: "Sélectionnez la date de l’événement pour vérifier la disponibilité du DJ.", checking: "Vérification...", dateAvailable: "Disponible à cette date", dateBooked: "Déjà réservé à cette date", dateUnavailable: "Indisponible à cette date", availabilityNotSet: "La disponibilité n’est pas définie. Vous pouvez tout de même envoyer une demande.", couldNotCheck: "Impossible de vérifier la disponibilité.", couldNotSave: "Impossible d’enregistrer la disponibilité." },
  de: { availableDates: "Verfügbare Termine", manageAvailability: "Buchungskalender", calendarHelp: "Datum antippen: Verfügbar → Gebucht → Nicht verfügbar → Nicht festgelegt.", available: "Verfügbar", booked: "Gebucht", unavailable: "Nicht verfügbar", notSet: "Nicht festgelegt", previousMonth: "Vorheriger Monat", nextMonth: "Nächster Monat", checkAvailability: "Verfügbarkeit prüfen", selectDate: "Wählen Sie das Veranstaltungsdatum, um die Verfügbarkeit zu prüfen.", checking: "Wird geprüft...", dateAvailable: "An diesem Datum verfügbar", dateBooked: "An diesem Datum bereits gebucht", dateUnavailable: "An diesem Datum nicht verfügbar", availabilityNotSet: "Die Verfügbarkeit ist nicht festgelegt. Sie können trotzdem anfragen.", couldNotCheck: "Verfügbarkeit konnte nicht geprüft werden.", couldNotSave: "Verfügbarkeit konnte nicht gespeichert werden." },
  ru: { availableDates: "Свободные даты", manageAvailability: "Календарь бронирований", calendarHelp: "Нажмите дату: Доступен → Забронирован → Недоступен → Не задано.", available: "Доступен", booked: "Забронирован", unavailable: "Недоступен", notSet: "Не задано", previousMonth: "Предыдущий месяц", nextMonth: "Следующий месяц", checkAvailability: "Проверить доступность", selectDate: "Выберите дату мероприятия, чтобы проверить доступность DJ.", checking: "Проверка...", dateAvailable: "Доступен в эту дату", dateBooked: "Уже забронирован в эту дату", dateUnavailable: "Недоступен в эту дату", availabilityNotSet: "Доступность не указана. Вы всё равно можете отправить запрос.", couldNotCheck: "Не удалось проверить доступность.", couldNotSave: "Не удалось сохранить доступность." },
  tr: { availableDates: "Uygun tarihler", manageAvailability: "Rezervasyon takvimi", calendarHelp: "Tarihe dokunun: Uygun → Rezerve → Uygun değil → Ayarlanmadı.", available: "Uygun", booked: "Rezerve", unavailable: "Uygun değil", notSet: "Ayarlanmadı", previousMonth: "Önceki ay", nextMonth: "Sonraki ay", checkAvailability: "Uygunluğu kontrol et", selectDate: "DJ’in uygunluğunu görmek için etkinlik tarihini seçin.", checking: "Kontrol ediliyor...", dateAvailable: "Bu tarihte uygun", dateBooked: "Bu tarihte zaten rezerve", dateUnavailable: "Bu tarihte uygun değil", availabilityNotSet: "Bu tarih için uygunluk ayarlanmamış. Yine de talep gönderebilirsiniz.", couldNotCheck: "Uygunluk kontrol edilemedi.", couldNotSave: "Uygunluk kaydedilemedi." },
  it: { availableDates: "Date disponibili", manageAvailability: "Calendario prenotazioni", calendarHelp: "Tocca una data: Disponibile → Prenotata → Non disponibile → Non impostata.", available: "Disponibile", booked: "Prenotata", unavailable: "Non disponibile", notSet: "Non impostata", previousMonth: "Mese precedente", nextMonth: "Mese successivo", checkAvailability: "Verifica disponibilità", selectDate: "Seleziona la data dell’evento per verificare la disponibilità del DJ.", checking: "Verifica...", dateAvailable: "Disponibile in questa data", dateBooked: "Già prenotato in questa data", dateUnavailable: "Non disponibile in questa data", availabilityNotSet: "La disponibilità non è impostata. Puoi comunque inviare una richiesta.", couldNotCheck: "Impossibile verificare la disponibilità.", couldNotSave: "Impossibile salvare la disponibilità." },
  nl: { availableDates: "Beschikbare data", manageAvailability: "Boekingskalender", calendarHelp: "Tik op een datum: Beschikbaar → Geboekt → Niet beschikbaar → Niet ingesteld.", available: "Beschikbaar", booked: "Geboekt", unavailable: "Niet beschikbaar", notSet: "Niet ingesteld", previousMonth: "Vorige maand", nextMonth: "Volgende maand", checkAvailability: "Beschikbaarheid controleren", selectDate: "Selecteer de evenementdatum om de beschikbaarheid te controleren.", checking: "Controleren...", dateAvailable: "Beschikbaar op deze datum", dateBooked: "Al geboekt op deze datum", dateUnavailable: "Niet beschikbaar op deze datum", availabilityNotSet: "Beschikbaarheid is niet ingesteld. Je kunt nog steeds een aanvraag sturen.", couldNotCheck: "Beschikbaarheid kon niet worden gecontroleerd.", couldNotSave: "Beschikbaarheid kon niet worden opgeslagen." },
  pl: { availableDates: "Dostępne terminy", manageAvailability: "Kalendarz rezerwacji", calendarHelp: "Dotknij daty: Dostępny → Zarezerwowany → Niedostępny → Nie ustawiono.", available: "Dostępny", booked: "Zarezerwowany", unavailable: "Niedostępny", notSet: "Nie ustawiono", previousMonth: "Poprzedni miesiąc", nextMonth: "Następny miesiąc", checkAvailability: "Sprawdź dostępność", selectDate: "Wybierz datę wydarzenia, aby sprawdzić dostępność DJ-a.", checking: "Sprawdzanie...", dateAvailable: "Dostępny w tym terminie", dateBooked: "Już zarezerwowany w tym terminie", dateUnavailable: "Niedostępny w tym terminie", availabilityNotSet: "Dostępność nie została ustawiona. Nadal możesz wysłać zapytanie.", couldNotCheck: "Nie udało się sprawdzić dostępności.", couldNotSave: "Nie udało się zapisać dostępności." },
  el: { availableDates: "Διαθέσιμες ημερομηνίες", manageAvailability: "Ημερολόγιο κρατήσεων", calendarHelp: "Πατήστε ημερομηνία: Διαθέσιμος → Κρατημένος → Μη διαθέσιμος → Δεν ορίστηκε.", available: "Διαθέσιμος", booked: "Κρατημένος", unavailable: "Μη διαθέσιμος", notSet: "Δεν ορίστηκε", previousMonth: "Προηγούμενος μήνας", nextMonth: "Επόμενος μήνας", checkAvailability: "Έλεγχος διαθεσιμότητας", selectDate: "Επιλέξτε ημερομηνία για να ελέγξετε τη διαθεσιμότητα του DJ.", checking: "Έλεγχος...", dateAvailable: "Διαθέσιμος αυτή την ημερομηνία", dateBooked: "Ήδη κρατημένος αυτή την ημερομηνία", dateUnavailable: "Μη διαθέσιμος αυτή την ημερομηνία", availabilityNotSet: "Η διαθεσιμότητα δεν έχει οριστεί. Μπορείτε ακόμη να στείλετε αίτημα.", couldNotCheck: "Δεν ήταν δυνατός ο έλεγχος.", couldNotSave: "Δεν ήταν δυνατή η αποθήκευση." },
  uk: { availableDates: "Доступні дати", manageAvailability: "Календар бронювань", calendarHelp: "Натисніть дату: Доступний → Заброньований → Недоступний → Не вказано.", available: "Доступний", booked: "Заброньований", unavailable: "Недоступний", notSet: "Не вказано", previousMonth: "Попередній місяць", nextMonth: "Наступний місяць", checkAvailability: "Перевірити доступність", selectDate: "Оберіть дату заходу, щоб перевірити доступність DJ.", checking: "Перевірка...", dateAvailable: "Доступний у цю дату", dateBooked: "Уже заброньований у цю дату", dateUnavailable: "Недоступний у цю дату", availabilityNotSet: "Доступність не вказана. Ви все одно можете надіслати запит.", couldNotCheck: "Не вдалося перевірити доступність.", couldNotSave: "Не вдалося зберегти доступність." },
};
