import type { Language } from "./translations";

type MarketplaceText = {
  eyebrow: string;
  title: string;
  description: string;
  publish: string;
  listed: string;
  hidden: string;
  serviceAreas: string;
  serviceAreasPlaceholder: string;
  genres: string;
  genresPlaceholder: string;
  languages: string;
  languagesPlaceholder: string;
  yearsExperience: string;
  travelDistance: string;
  commaHint: string;
  requirements: string;
};

const en: MarketplaceText = {
  eyebrow: "DJ MARKETPLACE",
  title: "Help clients find and book you",
  description: "Publish your profile in Blackline search and describe where and how you work.",
  publish: "List my profile",
  listed: "Visible in marketplace",
  hidden: "Not listed",
  serviceAreas: "Service areas",
  serviceAreasPlaceholder: "London, Manchester, Birmingham",
  genres: "Music genres",
  genresPlaceholder: "Afrobeats, Amapiano, Hip-hop",
  languages: "Languages spoken",
  languagesPlaceholder: "English, French, Twi",
  yearsExperience: "Years of experience",
  travelDistance: "Travel distance (km)",
  commaHint: "Separate multiple entries with commas.",
  requirements: "Before publishing, add a profile photo, bio, city, country, booking types and starting price.",
};

export const marketplaceTranslations: Record<Language, MarketplaceText> = {
  en,
  zh: { ...en, eyebrow: "DJ 市场", title: "帮助客户找到并预订你", description: "在 Blackline 搜索中发布你的资料，并说明你的服务地点和方式。", publish: "发布我的资料", listed: "市场中可见", hidden: "未发布", serviceAreas: "服务地区", genres: "音乐风格", languages: "使用语言", yearsExperience: "从业年数", travelDistance: "出行距离（公里）", commaHint: "多个项目请用逗号分隔。", requirements: "发布前，请添加头像、简介、城市、国家、预订类型和起始价格。" },
  ja: { ...en, eyebrow: "DJ マーケットプレイス", title: "お客様に見つけてもらい予約を獲得", description: "Blackline の検索にプロフィールを掲載し、活動地域やサービスを紹介します。", publish: "プロフィールを掲載", listed: "マーケットに公開中", hidden: "非公開", serviceAreas: "対応エリア", genres: "音楽ジャンル", languages: "対応言語", yearsExperience: "経験年数", travelDistance: "移動距離（km）", commaHint: "複数の項目はカンマで区切ってください。", requirements: "公開前に写真、紹介文、市、国、予約タイプ、開始価格を追加してください。" },
  ko: { ...en, eyebrow: "DJ 마켓플레이스", title: "고객이 나를 찾고 예약하도록 하세요", description: "Blackline 검색에 프로필을 공개하고 활동 지역과 서비스를 소개하세요.", publish: "내 프로필 등록", listed: "마켓에 공개됨", hidden: "등록 안 됨", serviceAreas: "서비스 지역", genres: "음악 장르", languages: "사용 언어", yearsExperience: "경력 연수", travelDistance: "이동 거리(km)", commaHint: "여러 항목은 쉼표로 구분하세요.", requirements: "공개 전에 사진, 소개, 도시, 국가, 예약 유형과 시작 가격을 추가하세요." },
  id: { ...en, eyebrow: "PASAR DJ", title: "Bantu klien menemukan dan memesan Anda", description: "Terbitkan profil Anda di pencarian Blackline dan jelaskan area serta layanan Anda.", publish: "Tampilkan profil saya", listed: "Terlihat di pasar", hidden: "Tidak ditampilkan", serviceAreas: "Area layanan", genres: "Genre musik", languages: "Bahasa yang dikuasai", yearsExperience: "Tahun pengalaman", travelDistance: "Jarak perjalanan (km)", commaHint: "Pisahkan beberapa entri dengan koma.", requirements: "Sebelum terbit, tambahkan foto, bio, kota, negara, jenis acara, dan harga awal." },
  ms: { ...en, eyebrow: "PASARAN DJ", title: "Bantu pelanggan mencari dan menempah anda", description: "Terbitkan profil anda dalam carian Blackline dan terangkan kawasan serta perkhidmatan anda.", publish: "Senaraikan profil saya", listed: "Kelihatan di pasaran", hidden: "Tidak disenaraikan", serviceAreas: "Kawasan perkhidmatan", genres: "Genre muzik", languages: "Bahasa pertuturan", yearsExperience: "Tahun pengalaman", travelDistance: "Jarak perjalanan (km)", commaHint: "Pisahkan beberapa entri dengan koma.", requirements: "Sebelum terbit, tambah foto, bio, bandar, negara, jenis tempahan dan harga permulaan." },
  th: { ...en, eyebrow: "ตลาด DJ", title: "ช่วยให้ลูกค้าค้นหาและจองคุณ", description: "เผยแพร่โปรไฟล์ในการค้นหา Blackline และระบุพื้นที่กับบริการของคุณ", publish: "ลงโปรไฟล์ของฉัน", listed: "แสดงในตลาด", hidden: "ยังไม่ลงรายการ", serviceAreas: "พื้นที่ให้บริการ", genres: "แนวเพลง", languages: "ภาษาที่พูด", yearsExperience: "ปีประสบการณ์", travelDistance: "ระยะทางเดินทาง (กม.)", commaHint: "คั่นหลายรายการด้วยเครื่องหมายจุลภาค", requirements: "ก่อนเผยแพร่ โปรดเพิ่มรูป Bio เมือง ประเทศ ประเภทงาน และราคาเริ่มต้น" },
  hi: { ...en, eyebrow: "DJ मार्केटप्लेस", title: "ग्राहकों को आपको खोजने और बुक करने दें", description: "Blackline खोज में अपनी प्रोफ़ाइल प्रकाशित करें और अपने क्षेत्र व सेवाएँ बताएं।", publish: "मेरी प्रोफ़ाइल सूचीबद्ध करें", listed: "मार्केटप्लेस में दिखाई दे रही है", hidden: "सूचीबद्ध नहीं", serviceAreas: "सेवा क्षेत्र", genres: "संगीत शैलियाँ", languages: "बोली जाने वाली भाषाएँ", yearsExperience: "अनुभव के वर्ष", travelDistance: "यात्रा दूरी (किमी)", commaHint: "कई प्रविष्टियों को कॉमा से अलग करें।", requirements: "प्रकाशित करने से पहले फोटो, परिचय, शहर, देश, बुकिंग प्रकार और शुरुआती कीमत जोड़ें।" },
  ar: { ...en, eyebrow: "سوق منسقي الأغاني", title: "ساعد العملاء في العثور عليك وحجزك", description: "انشر ملفك في بحث Blackline وحدد مناطق وخدمات عملك.", publish: "إدراج ملفي", listed: "ظاهر في السوق", hidden: "غير مدرج", serviceAreas: "مناطق الخدمة", genres: "أنواع الموسيقى", languages: "اللغات", yearsExperience: "سنوات الخبرة", travelDistance: "مسافة السفر (كم)", commaHint: "افصل بين العناصر بفواصل.", requirements: "قبل النشر أضف صورة ونبذة والمدينة والدولة وأنواع الحجز والسعر الابتدائي." },
  vi: { ...en, eyebrow: "CHỢ DJ", title: "Giúp khách hàng tìm và đặt lịch với bạn", description: "Đăng hồ sơ lên tìm kiếm Blackline và mô tả khu vực cùng dịch vụ của bạn.", publish: "Đăng hồ sơ của tôi", listed: "Hiển thị trên chợ", hidden: "Chưa đăng", serviceAreas: "Khu vực phục vụ", genres: "Thể loại nhạc", languages: "Ngôn ngữ", yearsExperience: "Số năm kinh nghiệm", travelDistance: "Khoảng cách di chuyển (km)", commaHint: "Phân cách nhiều mục bằng dấu phẩy.", requirements: "Trước khi đăng, hãy thêm ảnh, tiểu sử, thành phố, quốc gia, loại đặt lịch và giá khởi điểm." },
  tl: { ...en, eyebrow: "DJ MARKETPLACE", title: "Tulungan ang mga client na mahanap at i-book ka", description: "I-publish ang profile sa Blackline search at ilarawan ang lugar at serbisyo mo.", publish: "I-list ang profile ko", listed: "Nakikita sa marketplace", hidden: "Hindi naka-list", serviceAreas: "Mga lugar ng serbisyo", genres: "Mga genre ng musika", languages: "Mga wikang sinasalita", yearsExperience: "Taon ng karanasan", travelDistance: "Layo ng biyahe (km)", commaHint: "Paghiwalayin ang maraming entry gamit ang kuwit.", requirements: "Bago i-publish, magdagdag ng larawan, bio, lungsod, bansa, uri ng booking at panimulang presyo." },
  pt: { ...en, eyebrow: "MERCADO DE DJs", title: "Ajude clientes a encontrar e contratar você", description: "Publique seu perfil na busca Blackline e descreva onde e como trabalha.", publish: "Listar meu perfil", listed: "Visível no mercado", hidden: "Não listado", serviceAreas: "Áreas de atendimento", genres: "Gêneros musicais", languages: "Idiomas falados", yearsExperience: "Anos de experiência", travelDistance: "Distância de viagem (km)", commaHint: "Separe vários itens com vírgulas.", requirements: "Antes de publicar, adicione foto, bio, cidade, país, tipos de reserva e preço inicial." },
  es: { ...en, eyebrow: "MERCADO DE DJs", title: "Ayuda a los clientes a encontrarte y reservarte", description: "Publica tu perfil en la búsqueda de Blackline y describe dónde y cómo trabajas.", publish: "Publicar mi perfil", listed: "Visible en el mercado", hidden: "No publicado", serviceAreas: "Áreas de servicio", genres: "Géneros musicales", languages: "Idiomas hablados", yearsExperience: "Años de experiencia", travelDistance: "Distancia de viaje (km)", commaHint: "Separa varias entradas con comas.", requirements: "Antes de publicar, añade foto, biografía, ciudad, país, tipos de reserva y precio inicial." },
  fr: { ...en, eyebrow: "MARCHÉ DES DJs", title: "Aidez les clients à vous trouver et vous réserver", description: "Publiez votre profil dans la recherche Blackline et décrivez vos zones et services.", publish: "Publier mon profil", listed: "Visible sur le marché", hidden: "Non publié", serviceAreas: "Zones desservies", genres: "Genres musicaux", languages: "Langues parlées", yearsExperience: "Années d’expérience", travelDistance: "Distance de déplacement (km)", commaHint: "Séparez plusieurs éléments par des virgules.", requirements: "Avant de publier, ajoutez photo, bio, ville, pays, types de réservation et prix de départ." },
  de: { ...en, eyebrow: "DJ-MARKTPLATZ", title: "Hilf Kunden, dich zu finden und zu buchen", description: "Veröffentliche dein Profil in der Blackline-Suche und beschreibe Einsatzorte und Leistungen.", publish: "Mein Profil veröffentlichen", listed: "Im Marktplatz sichtbar", hidden: "Nicht gelistet", serviceAreas: "Einsatzgebiete", genres: "Musikgenres", languages: "Sprachen", yearsExperience: "Jahre Erfahrung", travelDistance: "Reisedistanz (km)", commaHint: "Mehrere Einträge durch Kommas trennen.", requirements: "Vor Veröffentlichung Foto, Bio, Stadt, Land, Buchungsarten und Startpreis ergänzen." },
  ru: { ...en, eyebrow: "МАРКЕТПЛЕЙС DJ", title: "Помогите клиентам найти и забронировать вас", description: "Опубликуйте профиль в поиске Blackline и укажите регионы и услуги.", publish: "Разместить мой профиль", listed: "Виден в маркетплейсе", hidden: "Не размещён", serviceAreas: "Регионы работы", genres: "Музыкальные жанры", languages: "Языки", yearsExperience: "Лет опыта", travelDistance: "Расстояние поездки (км)", commaHint: "Разделяйте несколько значений запятыми.", requirements: "Перед публикацией добавьте фото, описание, город, страну, типы бронирования и начальную цену." },
  tr: { ...en, eyebrow: "DJ PAZARYERİ", title: "Müşterilerin sizi bulup rezervasyon yapmasını sağlayın", description: "Profilinizi Blackline aramasında yayınlayın ve bölgelerinizi ve hizmetlerinizi açıklayın.", publish: "Profilimi listele", listed: "Pazaryerinde görünür", hidden: "Listelenmiyor", serviceAreas: "Hizmet bölgeleri", genres: "Müzik türleri", languages: "Konuşulan diller", yearsExperience: "Deneyim yılı", travelDistance: "Seyahat mesafesi (km)", commaHint: "Birden fazla girdiyi virgülle ayırın.", requirements: "Yayınlamadan önce fotoğraf, biyografi, şehir, ülke, rezervasyon türleri ve başlangıç fiyatı ekleyin." },
  it: { ...en, eyebrow: "MERCATO DJ", title: "Aiuta i clienti a trovarti e prenotarti", description: "Pubblica il profilo nella ricerca Blackline e descrivi zone e servizi.", publish: "Pubblica il mio profilo", listed: "Visibile nel mercato", hidden: "Non pubblicato", serviceAreas: "Zone servite", genres: "Generi musicali", languages: "Lingue parlate", yearsExperience: "Anni di esperienza", travelDistance: "Distanza di viaggio (km)", commaHint: "Separa più voci con virgole.", requirements: "Prima di pubblicare aggiungi foto, bio, città, paese, tipi di prenotazione e prezzo iniziale." },
  nl: { ...en, eyebrow: "DJ-MARKTPLAATS", title: "Help klanten je te vinden en boeken", description: "Publiceer je profiel in Blackline zoeken en beschrijf je regio’s en diensten.", publish: "Mijn profiel plaatsen", listed: "Zichtbaar op marktplaats", hidden: "Niet geplaatst", serviceAreas: "Werkgebieden", genres: "Muziekgenres", languages: "Gesproken talen", yearsExperience: "Jaren ervaring", travelDistance: "Reisafstand (km)", commaHint: "Scheid meerdere items met komma’s.", requirements: "Voeg voor publicatie een foto, bio, stad, land, boekingstypen en startprijs toe." },
  pl: { ...en, eyebrow: "RYNEK DJ-ÓW", title: "Pomóż klientom znaleźć i zarezerwować Ciebie", description: "Opublikuj profil w wyszukiwarce Blackline i opisz obszar oraz usługi.", publish: "Opublikuj mój profil", listed: "Widoczny na rynku", hidden: "Nieopublikowany", serviceAreas: "Obszary działania", genres: "Gatunki muzyczne", languages: "Języki", yearsExperience: "Lata doświadczenia", travelDistance: "Odległość dojazdu (km)", commaHint: "Oddziel wiele pozycji przecinkami.", requirements: "Przed publikacją dodaj zdjęcie, bio, miasto, kraj, typy rezerwacji i cenę początkową." },
  el: { ...en, eyebrow: "ΑΓΟΡΑ DJ", title: "Βοηθήστε τους πελάτες να σας βρουν και να σας κλείσουν", description: "Δημοσιεύστε το προφίλ σας στην αναζήτηση Blackline και περιγράψτε περιοχές και υπηρεσίες.", publish: "Δημοσίευση προφίλ", listed: "Ορατό στην αγορά", hidden: "Μη δημοσιευμένο", serviceAreas: "Περιοχές εξυπηρέτησης", genres: "Μουσικά είδη", languages: "Γλώσσες", yearsExperience: "Χρόνια εμπειρίας", travelDistance: "Απόσταση ταξιδιού (χλμ.)", commaHint: "Χωρίστε πολλαπλές τιμές με κόμματα.", requirements: "Πριν τη δημοσίευση προσθέστε φωτογραφία, βιογραφικό, πόλη, χώρα, τύπους κράτησης και αρχική τιμή." },
  uk: { ...en, eyebrow: "МАРКЕТПЛЕЙС DJ", title: "Допоможіть клієнтам знайти та забронювати вас", description: "Опублікуйте профіль у пошуку Blackline та опишіть регіони й послуги.", publish: "Опублікувати мій профіль", listed: "Видимий у маркетплейсі", hidden: "Не опублікований", serviceAreas: "Регіони роботи", genres: "Музичні жанри", languages: "Мови", yearsExperience: "Роки досвіду", travelDistance: "Відстань поїздки (км)", commaHint: "Розділяйте кілька значень комами.", requirements: "Перед публікацією додайте фото, опис, місто, країну, типи бронювання та початкову ціну." },
};
