import type { Language } from "./translations";

export type MyBlacklineTranslation = {
  language: string;
  title: string;
  subtitle: string;
  signIn: string;
  createAccount: string;
  name: string;
  email: string;
  password: string;
  signingIn: string;
  creating: string;
  checkEmail: string;
  myBookings: string;
  noBookings: string;
  noBookingsHelp: string;
  eventDate: string;
  venue: string;
  budget: string;
  payment: string;
  viewDj: string;
  signOut: string;
  loading: string;
  pending: string;
  accepted: string;
  rejected: string;
  awaitingPayment: string;
  confirmed: string;
  completed: string;
  cancelled: string;
};

export const myBlacklineTranslations: Record<Language, MyBlacklineTranslation> = {
  en: { language: "Language", title: "My Blackline", subtitle: "Keep every DJ booking in one secure place.", signIn: "Sign in", createAccount: "Create guest account", name: "Your name", email: "Email", password: "Password", signingIn: "Signing in...", creating: "Creating account...", checkEmail: "Check your email to confirm your account, then return here to sign in.", myBookings: "My Bookings", noBookings: "No bookings yet", noBookingsHelp: "Bookings made with this email will appear here.", eventDate: "Event date", venue: "Venue", budget: "Budget", payment: "Payment", viewDj: "View DJ", signOut: "Sign out", loading: "Loading your bookings...", pending: "Pending confirmation", accepted: "Accepted", rejected: "Rejected", awaitingPayment: "Awaiting payment", confirmed: "Confirmed", completed: "Completed", cancelled: "Cancelled" },
  zh: { language: "语言", title: "我的 Blackline", subtitle: "在一个安全的地方管理所有 DJ 预订。", signIn: "登录", createAccount: "创建客户账户", name: "你的姓名", email: "电子邮箱", password: "密码", signingIn: "正在登录...", creating: "正在创建账户...", checkEmail: "请查看邮件确认账户，然后返回登录。", myBookings: "我的预订", noBookings: "暂无预订", noBookingsHelp: "使用此邮箱提交的预订会显示在这里。", eventDate: "活动日期", venue: "场地", budget: "预算", payment: "付款", viewDj: "查看 DJ", signOut: "退出", loading: "正在加载预订...", pending: "等待确认", accepted: "已接受", rejected: "已拒绝", awaitingPayment: "等待付款", confirmed: "已确认", completed: "已完成", cancelled: "已取消" },
  ja: { language: "言語", title: "My Blackline", subtitle: "DJ予約を安全にまとめて管理できます。", signIn: "ログイン", createAccount: "ゲストアカウントを作成", name: "お名前", email: "メール", password: "パスワード", signingIn: "ログイン中...", creating: "作成中...", checkEmail: "メールを確認してアカウントを認証し、戻ってログインしてください。", myBookings: "予約一覧", noBookings: "予約はまだありません", noBookingsHelp: "このメールで行った予約がここに表示されます。", eventDate: "開催日", venue: "会場", budget: "予算", payment: "支払い", viewDj: "DJを見る", signOut: "ログアウト", loading: "予約を読み込み中...", pending: "確認待ち", accepted: "承認済み", rejected: "拒否", awaitingPayment: "支払い待ち", confirmed: "確定", completed: "完了", cancelled: "キャンセル" },
  ko: { language: "언어", title: "My Blackline", subtitle: "모든 DJ 예약을 안전하게 한곳에서 관리하세요.", signIn: "로그인", createAccount: "게스트 계정 만들기", name: "이름", email: "이메일", password: "비밀번호", signingIn: "로그인 중...", creating: "계정 생성 중...", checkEmail: "이메일에서 계정을 확인한 후 돌아와 로그인하세요.", myBookings: "내 예약", noBookings: "예약이 없습니다", noBookingsHelp: "이 이메일로 신청한 예약이 여기에 표시됩니다.", eventDate: "행사 날짜", venue: "장소", budget: "예산", payment: "결제", viewDj: "DJ 보기", signOut: "로그아웃", loading: "예약 불러오는 중...", pending: "확인 대기", accepted: "수락됨", rejected: "거절됨", awaitingPayment: "결제 대기", confirmed: "확정됨", completed: "완료", cancelled: "취소됨" },
  id: { language: "Bahasa", title: "Blackline Saya", subtitle: "Simpan semua pemesanan DJ dengan aman di satu tempat.", signIn: "Masuk", createAccount: "Buat akun tamu", name: "Nama Anda", email: "Email", password: "Kata sandi", signingIn: "Sedang masuk...", creating: "Membuat akun...", checkEmail: "Periksa email untuk mengonfirmasi akun, lalu kembali untuk masuk.", myBookings: "Pemesanan Saya", noBookings: "Belum ada pemesanan", noBookingsHelp: "Pemesanan dengan email ini akan muncul di sini.", eventDate: "Tanggal acara", venue: "Lokasi", budget: "Anggaran", payment: "Pembayaran", viewDj: "Lihat DJ", signOut: "Keluar", loading: "Memuat pemesanan...", pending: "Menunggu konfirmasi", accepted: "Diterima", rejected: "Ditolak", awaitingPayment: "Menunggu pembayaran", confirmed: "Dikonfirmasi", completed: "Selesai", cancelled: "Dibatalkan" },
  ms: { language: "Bahasa", title: "Blackline Saya", subtitle: "Simpan semua tempahan DJ dengan selamat di satu tempat.", signIn: "Log masuk", createAccount: "Cipta akaun tetamu", name: "Nama anda", email: "E-mel", password: "Kata laluan", signingIn: "Sedang log masuk...", creating: "Mencipta akaun...", checkEmail: "Semak e-mel untuk mengesahkan akaun, kemudian kembali untuk log masuk.", myBookings: "Tempahan Saya", noBookings: "Belum ada tempahan", noBookingsHelp: "Tempahan menggunakan e-mel ini akan muncul di sini.", eventDate: "Tarikh acara", venue: "Tempat", budget: "Bajet", payment: "Bayaran", viewDj: "Lihat DJ", signOut: "Log keluar", loading: "Memuatkan tempahan...", pending: "Menunggu pengesahan", accepted: "Diterima", rejected: "Ditolak", awaitingPayment: "Menunggu bayaran", confirmed: "Disahkan", completed: "Selesai", cancelled: "Dibatalkan" },
  th: { language: "ภาษา", title: "Blackline ของฉัน", subtitle: "เก็บการจองดีเจทั้งหมดไว้อย่างปลอดภัยในที่เดียว", signIn: "เข้าสู่ระบบ", createAccount: "สร้างบัญชีผู้จอง", name: "ชื่อของคุณ", email: "อีเมล", password: "รหัสผ่าน", signingIn: "กำลังเข้าสู่ระบบ...", creating: "กำลังสร้างบัญชี...", checkEmail: "ตรวจสอบอีเมลเพื่อยืนยันบัญชี แล้วกลับมาเข้าสู่ระบบ", myBookings: "การจองของฉัน", noBookings: "ยังไม่มีการจอง", noBookingsHelp: "การจองด้วยอีเมลนี้จะแสดงที่นี่", eventDate: "วันที่จัดงาน", venue: "สถานที่", budget: "งบประมาณ", payment: "การชำระเงิน", viewDj: "ดู DJ", signOut: "ออกจากระบบ", loading: "กำลังโหลดการจอง...", pending: "รอยืนยัน", accepted: "ยอมรับแล้ว", rejected: "ปฏิเสธแล้ว", awaitingPayment: "รอชำระเงิน", confirmed: "ยืนยันแล้ว", completed: "เสร็จสิ้น", cancelled: "ยกเลิกแล้ว" },
  hi: { language: "भाषा", title: "मेरा Blackline", subtitle: "अपनी सभी DJ बुकिंग एक सुरक्षित जगह पर रखें।", signIn: "साइन इन", createAccount: "अतिथि खाता बनाएँ", name: "आपका नाम", email: "ईमेल", password: "पासवर्ड", signingIn: "साइन इन हो रहा है...", creating: "खाता बन रहा है...", checkEmail: "खाता पुष्टि के लिए ईमेल देखें, फिर यहाँ साइन इन करें।", myBookings: "मेरी बुकिंग", noBookings: "अभी कोई बुकिंग नहीं", noBookingsHelp: "इस ईमेल से की गई बुकिंग यहाँ दिखेगी।", eventDate: "कार्यक्रम की तारीख", venue: "स्थान", budget: "बजट", payment: "भुगतान", viewDj: "DJ देखें", signOut: "साइन आउट", loading: "बुकिंग लोड हो रही हैं...", pending: "पुष्टि लंबित", accepted: "स्वीकृत", rejected: "अस्वीकृत", awaitingPayment: "भुगतान लंबित", confirmed: "पुष्ट", completed: "पूर्ण", cancelled: "रद्द" },
  ar: { language: "اللغة", title: "Blackline الخاص بي", subtitle: "احتفظ بجميع حجوزات DJ في مكان آمن واحد.", signIn: "تسجيل الدخول", createAccount: "إنشاء حساب ضيف", name: "اسمك", email: "البريد الإلكتروني", password: "كلمة المرور", signingIn: "جارٍ تسجيل الدخول...", creating: "جارٍ إنشاء الحساب...", checkEmail: "تحقق من بريدك لتأكيد الحساب، ثم عد لتسجيل الدخول.", myBookings: "حجوزاتي", noBookings: "لا توجد حجوزات بعد", noBookingsHelp: "ستظهر هنا الحجوزات التي تمت بهذا البريد.", eventDate: "تاريخ المناسبة", venue: "المكان", budget: "الميزانية", payment: "الدفع", viewDj: "عرض DJ", signOut: "تسجيل الخروج", loading: "جارٍ تحميل الحجوزات...", pending: "بانتظار التأكيد", accepted: "مقبول", rejected: "مرفوض", awaitingPayment: "بانتظار الدفع", confirmed: "مؤكد", completed: "مكتمل", cancelled: "ملغي" },
  vi: { language: "Ngôn ngữ", title: "Blackline của tôi", subtitle: "Lưu mọi đặt DJ an toàn tại một nơi.", signIn: "Đăng nhập", createAccount: "Tạo tài khoản khách", name: "Tên của bạn", email: "Email", password: "Mật khẩu", signingIn: "Đang đăng nhập...", creating: "Đang tạo tài khoản...", checkEmail: "Kiểm tra email để xác nhận tài khoản, rồi quay lại đăng nhập.", myBookings: "Đặt chỗ của tôi", noBookings: "Chưa có đặt chỗ", noBookingsHelp: "Đặt chỗ bằng email này sẽ xuất hiện ở đây.", eventDate: "Ngày sự kiện", venue: "Địa điểm", budget: "Ngân sách", payment: "Thanh toán", viewDj: "Xem DJ", signOut: "Đăng xuất", loading: "Đang tải đặt chỗ...", pending: "Chờ xác nhận", accepted: "Đã chấp nhận", rejected: "Đã từ chối", awaitingPayment: "Chờ thanh toán", confirmed: "Đã xác nhận", completed: "Hoàn tất", cancelled: "Đã hủy" },
  tl: { language: "Wika", title: "Aking Blackline", subtitle: "Panatilihing ligtas sa isang lugar ang lahat ng DJ booking.", signIn: "Mag-sign in", createAccount: "Gumawa ng guest account", name: "Iyong pangalan", email: "Email", password: "Password", signingIn: "Nagsa-sign in...", creating: "Gumagawa ng account...", checkEmail: "Tingnan ang email para kumpirmahin ang account, saka bumalik para mag-sign in.", myBookings: "Aking Mga Booking", noBookings: "Wala pang booking", noBookingsHelp: "Lalabas dito ang booking gamit ang email na ito.", eventDate: "Petsa ng event", venue: "Lugar", budget: "Badyet", payment: "Bayad", viewDj: "Tingnan ang DJ", signOut: "Mag-sign out", loading: "Nilo-load ang bookings...", pending: "Naghihintay ng kumpirmasyon", accepted: "Tinanggap", rejected: "Tinanggihan", awaitingPayment: "Naghihintay ng bayad", confirmed: "Kumpirmado", completed: "Tapos na", cancelled: "Kinansela" },
  pt: { language: "Idioma", title: "Meu Blackline", subtitle: "Guarde todas as reservas de DJ com segurança num só lugar.", signIn: "Entrar", createAccount: "Criar conta de cliente", name: "Seu nome", email: "E-mail", password: "Palavra-passe", signingIn: "A entrar...", creating: "A criar conta...", checkEmail: "Verifique o e-mail para confirmar a conta e depois volte para entrar.", myBookings: "Minhas Reservas", noBookings: "Ainda não há reservas", noBookingsHelp: "As reservas feitas com este e-mail aparecerão aqui.", eventDate: "Data do evento", venue: "Local", budget: "Orçamento", payment: "Pagamento", viewDj: "Ver DJ", signOut: "Sair", loading: "A carregar reservas...", pending: "Confirmação pendente", accepted: "Aceite", rejected: "Rejeitada", awaitingPayment: "A aguardar pagamento", confirmed: "Confirmada", completed: "Concluída", cancelled: "Cancelada" },
  es: { language: "Idioma", title: "Mi Blackline", subtitle: "Guarda todas tus reservas de DJ de forma segura en un solo lugar.", signIn: "Iniciar sesión", createAccount: "Crear cuenta de invitado", name: "Tu nombre", email: "Correo electrónico", password: "Contraseña", signingIn: "Iniciando sesión...", creating: "Creando cuenta...", checkEmail: "Revisa tu correo para confirmar la cuenta y vuelve para iniciar sesión.", myBookings: "Mis Reservas", noBookings: "Aún no hay reservas", noBookingsHelp: "Las reservas hechas con este correo aparecerán aquí.", eventDate: "Fecha del evento", venue: "Lugar", budget: "Presupuesto", payment: "Pago", viewDj: "Ver DJ", signOut: "Cerrar sesión", loading: "Cargando reservas...", pending: "Pendiente de confirmación", accepted: "Aceptada", rejected: "Rechazada", awaitingPayment: "Esperando pago", confirmed: "Confirmada", completed: "Completada", cancelled: "Cancelada" },
  fr: { language: "Langue", title: "Mon Blackline", subtitle: "Conservez toutes vos réservations DJ en sécurité au même endroit.", signIn: "Se connecter", createAccount: "Créer un compte client", name: "Votre nom", email: "E-mail", password: "Mot de passe", signingIn: "Connexion...", creating: "Création du compte...", checkEmail: "Consultez votre e-mail pour confirmer le compte, puis revenez vous connecter.", myBookings: "Mes Réservations", noBookings: "Aucune réservation", noBookingsHelp: "Les réservations faites avec cet e-mail apparaîtront ici.", eventDate: "Date de l’événement", venue: "Lieu", budget: "Budget", payment: "Paiement", viewDj: "Voir le DJ", signOut: "Se déconnecter", loading: "Chargement des réservations...", pending: "En attente de confirmation", accepted: "Acceptée", rejected: "Refusée", awaitingPayment: "En attente de paiement", confirmed: "Confirmée", completed: "Terminée", cancelled: "Annulée" },
  de: { language: "Sprache", title: "Mein Blackline", subtitle: "Alle DJ-Buchungen sicher an einem Ort verwalten.", signIn: "Anmelden", createAccount: "Gastkonto erstellen", name: "Dein Name", email: "E-Mail", password: "Passwort", signingIn: "Anmeldung...", creating: "Konto wird erstellt...", checkEmail: "Bestätige dein Konto per E-Mail und melde dich danach hier an.", myBookings: "Meine Buchungen", noBookings: "Noch keine Buchungen", noBookingsHelp: "Buchungen mit dieser E-Mail erscheinen hier.", eventDate: "Veranstaltungsdatum", venue: "Ort", budget: "Budget", payment: "Zahlung", viewDj: "DJ ansehen", signOut: "Abmelden", loading: "Buchungen werden geladen...", pending: "Bestätigung ausstehend", accepted: "Angenommen", rejected: "Abgelehnt", awaitingPayment: "Zahlung ausstehend", confirmed: "Bestätigt", completed: "Abgeschlossen", cancelled: "Storniert" },
  ru: { language: "Язык", title: "Мой Blackline", subtitle: "Все бронирования DJ в одном безопасном месте.", signIn: "Войти", createAccount: "Создать аккаунт гостя", name: "Ваше имя", email: "Эл. почта", password: "Пароль", signingIn: "Вход...", creating: "Создание аккаунта...", checkEmail: "Подтвердите аккаунт по электронной почте, затем вернитесь для входа.", myBookings: "Мои бронирования", noBookings: "Бронирований пока нет", noBookingsHelp: "Бронирования с этой почтой появятся здесь.", eventDate: "Дата мероприятия", venue: "Место", budget: "Бюджет", payment: "Оплата", viewDj: "Открыть DJ", signOut: "Выйти", loading: "Загрузка бронирований...", pending: "Ожидает подтверждения", accepted: "Принято", rejected: "Отклонено", awaitingPayment: "Ожидает оплаты", confirmed: "Подтверждено", completed: "Завершено", cancelled: "Отменено" },
  tr: { language: "Dil", title: "Blackline’ım", subtitle: "Tüm DJ rezervasyonlarını tek bir güvenli yerde tutun.", signIn: "Giriş yap", createAccount: "Misafir hesabı oluştur", name: "Adınız", email: "E-posta", password: "Şifre", signingIn: "Giriş yapılıyor...", creating: "Hesap oluşturuluyor...", checkEmail: "Hesabı doğrulamak için e-postanızı kontrol edin, ardından giriş yapın.", myBookings: "Rezervasyonlarım", noBookings: "Henüz rezervasyon yok", noBookingsHelp: "Bu e-postayla yapılan rezervasyonlar burada görünür.", eventDate: "Etkinlik tarihi", venue: "Mekân", budget: "Bütçe", payment: "Ödeme", viewDj: "DJ’yi görüntüle", signOut: "Çıkış yap", loading: "Rezervasyonlar yükleniyor...", pending: "Onay bekliyor", accepted: "Kabul edildi", rejected: "Reddedildi", awaitingPayment: "Ödeme bekliyor", confirmed: "Onaylandı", completed: "Tamamlandı", cancelled: "İptal edildi" },
  it: { language: "Lingua", title: "Il mio Blackline", subtitle: "Conserva tutte le prenotazioni DJ in un unico posto sicuro.", signIn: "Accedi", createAccount: "Crea account ospite", name: "Il tuo nome", email: "Email", password: "Password", signingIn: "Accesso...", creating: "Creazione account...", checkEmail: "Controlla l’email per confermare l’account, poi torna ad accedere.", myBookings: "Le mie prenotazioni", noBookings: "Nessuna prenotazione", noBookingsHelp: "Le prenotazioni con questa email appariranno qui.", eventDate: "Data evento", venue: "Luogo", budget: "Budget", payment: "Pagamento", viewDj: "Vedi DJ", signOut: "Esci", loading: "Caricamento prenotazioni...", pending: "In attesa di conferma", accepted: "Accettata", rejected: "Rifiutata", awaitingPayment: "In attesa di pagamento", confirmed: "Confermata", completed: "Completata", cancelled: "Annullata" },
  nl: { language: "Taal", title: "Mijn Blackline", subtitle: "Bewaar al je DJ-boekingen veilig op één plek.", signIn: "Inloggen", createAccount: "Gastaccount maken", name: "Je naam", email: "E-mail", password: "Wachtwoord", signingIn: "Inloggen...", creating: "Account maken...", checkEmail: "Bevestig je account via e-mail en kom terug om in te loggen.", myBookings: "Mijn Boekingen", noBookings: "Nog geen boekingen", noBookingsHelp: "Boekingen met dit e-mailadres verschijnen hier.", eventDate: "Evenementdatum", venue: "Locatie", budget: "Budget", payment: "Betaling", viewDj: "Bekijk DJ", signOut: "Uitloggen", loading: "Boekingen laden...", pending: "Wacht op bevestiging", accepted: "Geaccepteerd", rejected: "Afgewezen", awaitingPayment: "Wacht op betaling", confirmed: "Bevestigd", completed: "Voltooid", cancelled: "Geannuleerd" },
  pl: { language: "Język", title: "Mój Blackline", subtitle: "Przechowuj wszystkie rezerwacje DJ-a bezpiecznie w jednym miejscu.", signIn: "Zaloguj się", createAccount: "Utwórz konto gościa", name: "Twoje imię", email: "E-mail", password: "Hasło", signingIn: "Logowanie...", creating: "Tworzenie konta...", checkEmail: "Potwierdź konto przez e-mail, a następnie wróć, aby się zalogować.", myBookings: "Moje Rezerwacje", noBookings: "Brak rezerwacji", noBookingsHelp: "Rezerwacje z tym adresem e-mail pojawią się tutaj.", eventDate: "Data wydarzenia", venue: "Miejsce", budget: "Budżet", payment: "Płatność", viewDj: "Zobacz DJ-a", signOut: "Wyloguj", loading: "Ładowanie rezerwacji...", pending: "Oczekuje na potwierdzenie", accepted: "Przyjęta", rejected: "Odrzucona", awaitingPayment: "Oczekuje na płatność", confirmed: "Potwierdzona", completed: "Zakończona", cancelled: "Anulowana" },
  el: { language: "Γλώσσα", title: "Το Blackline μου", subtitle: "Κρατήστε όλες τις κρατήσεις DJ ασφαλείς σε ένα μέρος.", signIn: "Σύνδεση", createAccount: "Δημιουργία λογαριασμού επισκέπτη", name: "Το όνομά σας", email: "Email", password: "Κωδικός", signingIn: "Σύνδεση...", creating: "Δημιουργία λογαριασμού...", checkEmail: "Επιβεβαιώστε τον λογαριασμό από το email και επιστρέψτε για σύνδεση.", myBookings: "Οι Κρατήσεις μου", noBookings: "Δεν υπάρχουν κρατήσεις", noBookingsHelp: "Οι κρατήσεις με αυτό το email θα εμφανιστούν εδώ.", eventDate: "Ημερομηνία εκδήλωσης", venue: "Χώρος", budget: "Προϋπολογισμός", payment: "Πληρωμή", viewDj: "Προβολή DJ", signOut: "Αποσύνδεση", loading: "Φόρτωση κρατήσεων...", pending: "Αναμονή επιβεβαίωσης", accepted: "Αποδεκτή", rejected: "Απορρίφθηκε", awaitingPayment: "Αναμονή πληρωμής", confirmed: "Επιβεβαιωμένη", completed: "Ολοκληρωμένη", cancelled: "Ακυρώθηκε" },
  uk: { language: "Мова", title: "Мій Blackline", subtitle: "Зберігайте всі бронювання DJ безпечно в одному місці.", signIn: "Увійти", createAccount: "Створити гостьовий акаунт", name: "Ваше ім’я", email: "Електронна пошта", password: "Пароль", signingIn: "Вхід...", creating: "Створення акаунта...", checkEmail: "Підтвердьте акаунт через електронну пошту, потім поверніться для входу.", myBookings: "Мої Бронювання", noBookings: "Бронювань ще немає", noBookingsHelp: "Бронювання з цією поштою з’являться тут.", eventDate: "Дата події", venue: "Місце", budget: "Бюджет", payment: "Оплата", viewDj: "Переглянути DJ", signOut: "Вийти", loading: "Завантаження бронювань...", pending: "Очікує підтвердження", accepted: "Прийнято", rejected: "Відхилено", awaitingPayment: "Очікує оплати", confirmed: "Підтверджено", completed: "Завершено", cancelled: "Скасовано" },
};
